export type UserRole = 'ceo' | 'it_admin' | 'consultant';

export type FollowUpSymbol = '*' | '+' | '-' | '.' | '✓' | '';

export interface FollowUpStatusCode {
  code: FollowUpSymbol;
  symbol: string;
  label: string;
  meaning: string;
  colorClass: string;
  badgeClass: string;
  bgClass: string;
  textColor: string;
  borderColor: string;
}

export type UserStatus = 'active' | 'suspended' | 'archived' | 'terminated';

export interface User {
  id: string;
  username: string;
  fullName: string;
  consultantCode: string;
  role: UserRole;
  status?: UserStatus;
  password?: string;
  avatar?: string;
  phone?: string;
  branch?: string;
  updatedAt?: string;
}

export interface ReportRow {
  id: string;
  rowNumber: number;
  clientName: string; // نام و نام خانوادگی کارفرما
  activityField: string; // زمینه فعالیت / صنف
  personnelCount?: number | string; // تعداد پرسنل (اختیاری)
  phone: string; // شماره تماس
  address: string; // آدرس
  employerConcern: string; // دغدغه کارفرما (از لیست ۲۵ تایی)
  followUp1: string; // پیگیری ۱
  followUp2: string; // پیگیری ۲
  followUp3: string; // پیگیری ۳
  followUp4: string; // پیگیری ۴
  followUp1Date?: string; // تاریخ انجام پیگیری ۱ (ISO string)
  followUp2Date?: string; // تاریخ انجام پیگیری ۲ (ISO string)
  followUp3Date?: string; // تاریخ انجام پیگیری ۳ (ISO string)
  followUp4Date?: string; // تاریخ انجام پیگیری ۴ (ISO string)
  followUp1DateShamsi?: string; // تاریخ دقیق شمسی پیگیری ۱ (مثلاً 1405/06/13)
  followUp2DateShamsi?: string; // تاریخ دقیق شمسی پیگیری ۲ (مثلاً 1405/06/17)
  followUp3DateShamsi?: string; // تاریخ دقیق شمسی پیگیری ۳ (مثلاً 1405/06/18)
  followUp4DateShamsi?: string; // تاریخ دقیق شمسی پیگیری ۴ (مثلاً 1405/06/22)
  followUpResult: string; // نتیجه پیگیری
  meetingTopic: string; // موضوع جلسه
  notes?: string;
}

export interface DailyReport {
  id: string;
  consultantId: string;
  consultantName: string;
  consultantCode: string;
  guild: string; // صنف کلی گزارش
  dateShamsi: string; // تاریخ شمسی
  dayOfWeekShamsi: string; // روز هفته
  createdAt: string; // ISO string
  submittedAt: string; // ساعت ارسال
  status: 'submitted' | 'approved' | 'needs_review';
  personalOpinion: string; // نظر شخصی مشاور درباره فعالیت روزانه
  rows: ReportRow[];
  managerFeedback?: string;
  managerRating?: number; // 1 to 5 stars
  reviewedAt?: string;
  updatedAt?: string; // ISO string of last edit/follow-up modification
}

export type ArchiveType = 'calls_daily' | 'periodic_daily' | 'periodic_weekly' | 'periodic_monthly';

export interface ArchiveRecord {
  id: string;
  fileName: string; // e.g. "بایگانی_تماسها_و_پیگیری_روزانه_دوشنبه_1405-06-19.xlsx"
  dateShamsi: string;
  dayOfWeek: string;
  timestamp: string;
  archiveType?: ArchiveType; // defaults to 'calls_daily'
  periodTitle?: string;
  totalConsultants: number;
  totalClientsContacted: number;
  topConcerns: { name: string; count: number }[];
  reports: DailyReport[];
  overallReports?: PeriodicOverallReport[];
  autoGenerated: boolean;
}

export interface AIAnalysisResult {
  summary: string;
  overallScore: number;
  topTrends: string[];
  consultantEvaluations: {
    consultantName: string;
    consultantCode: string;
    performanceRating: string;
    strengths: string[];
    weaknessesOrFollowUps: string[];
    aiRecommendation: string;
  }[];
  marketOpportunities: string[];
  strategicActionItems: string[];
}

export interface ManagerDirective {
  id: string;
  targetConsultantId: string; // 'all' or specific consultantId/code
  targetConsultantName?: string;
  authorId?: string;
  authorName: string;
  content: string; // e.g. "پرونده کریمی رو اولویت بده"
  priority: 'high' | 'normal';
  createdAt: string;
  dateShamsi: string;
}

export interface UpcomingFollowUpItem {
  reportId: string;
  reportDateShamsi: string;
  createdAt: string;
  guild: string;
  rowNumber: number;
  rowId: string;
  clientName: string;
  activityField: string;
  phone: string;
  address: string;
  employerConcern: string;
  meetingTopic: string;
  followUp1: string;
  followUp2: string;
  followUp3: string;
  followUp4: string;
  followUpResult: string;
  nextStepNumber: number; // 2, 3, or 4
  elapsedDays: number;
  daysRemaining: number;
  statusCategory: 'today' | 'overdue' | 'future';
}

export type OverallReportPeriodType = 'daily' | 'weekly' | 'monthly';
export type PeriodicReportType = OverallReportPeriodType;

export interface PeriodicOverallReport {
  id: string;
  consultantId: string;
  consultantName: string;
  consultantCode: string;
  periodType: OverallReportPeriodType; // 'daily' | 'weekly' | 'monthly'
  dateShamsi: string; // تاریخ موعد گزارش (مثلاً 1405/06/19 برای روزانه، تاریخ پنج‌شنبه برای هفتگی، و تاریخ پایان ماه برای ماهانه)
  periodLabel: string; // e.g. "گزارش روزانه پنج‌شنبه ۱۹ شهریور" | "گزارش هفتگی هفته سوم شهریور" | "گزارش ماهانه شهریور ۱۴۰۵"
  
  // فیلدهای محتوایی
  summary: string; // تحلیل و ارزیابی کلی عملکرد
  keyAchievements?: string; // دستاوردها و نتایج کلیدی (جلسات قطعی، توافقات)
  challengesOrBarriers?: string; // چالش‌ها و موانع برخورد شده
  plansOrPriorities?: string; // برنامه‌ها و اولویت‌های کاری فردا / دوره بعد
  selfRating?: number; // خودارزیابی مشاور (۱ تا ۵)
  hasSetMeeting?: boolean; // جلسه ست شد (مربوط به نماد ✓)
  autoFollowUpEnabled?: boolean; // پیگیری خودکار هوشمند (همواره فعال/disabled)
  
  // فیلدهای ویژه دوره‌های هفتگی و ماهانه
  weeklyFocusGuilds?: string; // ارزیابی صنوف و صنایع کانون توجه (ویژه هفتگی)
  monthlyStrategicNotes?: string; // پیشنهادات کلان و استراتژیک به سرپرست (ویژه ماهانه)

  submittedAt: string; // زمان ارسال (ساعت یا فرمت فارسی)
  createdAt: string; // ISO
  updatedAt?: string;

  // نظارت و ارزیابی مدیر
  managerFeedback?: string;
  managerRating?: number; // 1 to 5
  managerStatus?: 'approved' | 'rewarded' | 'warned' | 'pending';
  managerReviewedAt?: string;
}

// -----------------------------------------------------------
// 25-ROW LEAD SHEET ENGINE & ENTERPRISE DISPATCH TYPES
// -----------------------------------------------------------

export type LeadRowStatus = 'in_progress' | 'won' | 'lost' | 'invalid';

export interface LeadRow {
  id: string;
  rowNumber: number; // 1 to 25
  clientName: string; // نام و نام خانوادگی کارفرما
  activityField: string; // زمینه فعالیت / صنف
  personnelCount?: number | string; // تعداد پرسنل
  phone: string; // شماره تماس
  address: string; // آدرس
  followUp1?: string; // پیگیری ۱ (نماد)
  followUp1Date?: string; // تاریخ میلادی
  followUp1DateShamsi?: string; // تاریخ شمسی
  followUp2?: string; // پیگیری ۲
  followUp2Date?: string;
  followUp2DateShamsi?: string;
  followUp3?: string; // پیگیری ۳
  followUp3Date?: string;
  followUp3DateShamsi?: string;
  followUp4?: string; // پیگیری ۴
  followUp4Date?: string;
  employerConcern?: string; // دغدغه کارفرما
  followUpResult?: string; // نتیجه پیگیری
  meetingTopic?: string; // موضوع جلسه و بسته پیشنهادی
  status?: LeadRowStatus; // وضعیت ردیف
  notes?: string;
  updatedAt?: string;
}

export type LeadSheetStatus = 'active' | 'completed' | 'archived';

export interface LeadSheet {
  id: string;
  sheetNumber: number;
  title: string;
  guild: string;
  assignedToConsultantId: string;
  assignedToConsultantName: string;
  assignedToConsultantCode: string;
  assignedByManagerId?: string;
  assignedAt: string; // ISO
  dateShamsi: string; // تاریخ تخصیص شمسی
  targetCallsCount: number; // معمولاً ۲۵
  rows: LeadRow[];
  status: LeadSheetStatus;
  completedAt?: string;
  archivedAt?: string;
  managerNotes?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface SheetMessage {
  id: string;
  sheetId: string;
  rowId: string;
  clientName?: string;
  senderId: string;
  senderName: string;
  senderRole: UserRole;
  content: string;
  createdAt: string;
  timeShamsi: string;
  isRead: boolean;
}

export type MemoCategory = 'directive' | 'warning' | 'report_request' | 'consultant_query' | 'other';
export type MemoPriority = 'normal' | 'urgent';

export interface MemoMessage {
  id: string;
  memoNumber: string;
  senderId: string;
  senderName: string;
  senderRole: UserRole;
  recipientId: string; // 'all' or specific consultantId/userId
  recipientName: string;
  title: string;
  content: string;
  priority: MemoPriority;
  category: MemoCategory;
  relatedSheetId?: string;
  createdAt: string;
  dateShamsi: string;
  isRead: boolean;
}




